stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  image: node:latest  # 如果 Runner 配置了 pull_policy="if-not-present"，会优先用本地镜像
  script:
    - echo "building wiki..."
    - yarn install
    - yarn build
    - rm -rf /out/build || true
    - cp -r ./build /out/
    - chown -R 1000:1000 /out/build
  tags:
    - wiki-runner